### ISSUE TITLE
AWSInstanceSchedulerMain is not authorized to perform: lambda:InvokeFunction

### ISSUE THREAD

**Issue by ptrhck** [awslabs/aws-instance-scheduler#219]
I have deployed the template using AWS CLI, but the instances are not stopped. I can see the following error in the CloudWatch logs:

```
{ "version": "0", "id": "1afc350e-9055-a388-d580-e2fec6b3fb16", "detail-type": "Scheduled Event", "source": "aws.events", "account": "xxx", "time": "2020-11-26T22:00:00Z", "region": "eu-central-1", "resources": [ "arn:aws:events:eu-central-1:xx:rule/aws-instance-schedulerscheduling_rule" ], "detail": {} }
by handler CloudWatchEventHandler: (An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::xxx:assumed-role/instance-scheduler-InstanceScheduler-SchedulerRole-13CTQLNULTQR0/AWSInstanceSchedulerMain is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-central-1:xxx:function:AWSInstanceSchedulerMain)
Traceback (most recent call last):
File "/var/task/main.py", line 71, in lambda_handler
result = handler.handle_request()
File "/var/task/requesthandlers/cloudwatch_event_handler.py", line 215, in handle_request
return self._run_schedulers_as_lambda(number_of_accounts, number_of_regions, number_of_services)
File "/var/task/requesthandlers/cloudwatch_event_handler.py", line 240, in _run_schedulers_as_lambda
result.append(self._execute_as_lambda(level_configuration))
File "/var/task/requesthandlers/cloudwatch_event_handler.py", line 293, in _execute_as_lambda
InvocationType="Event", LogType="None", Payload=payload)
File "/var/task/boto_retry/_init_.py", line 78, in wrapped_api_method
return retry_strategy.call(client_or_resource, name, args)
File "/var/task/boto_retry/aws_service_retry.py", line 136, in call
raise ex
File "/var/task/boto_retry/aws_service_retry.py", line 118, in call
resp = method(**call_arguments)
File "/var/runtime/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 676, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::xxx:assumed-role/instance-scheduler-InstanceScheduler-SchedulerRole-13CTQLNULTQR0/AWSInstanceSchedulerMain is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-central-1:xxx:function:AWSInstanceSchedulerMain
```

Any ideas?

**Comment by gockle** [comment]
Hi @ptrhck Can you confirm if the lambda role that was created once the stack launched successfully has the following policy documentation in the Trust Relationship 

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "lambda.amazonaws.com",
          "events.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Comment by ptrhck** [comment]
I have used it as a substack and its name was then just too long. All working fine now! Cheers :)
