### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by mrichman** [awslabs/aws-instance-scheduler#68]
When running `scheduler-cli` immediately after install, I get this error:

```
$ scheduler-cli
Traceback (most recent call last):
  File "/usr/local/bin/scheduler-cli", line 11, in <module>
    load_entry_point('scheduler-cli==2.2.2.0', 'console_scripts', 'scheduler-cli')()
  File "/usr/local/lib/python3.7/site-packages/scheduler_cli-2.2.2.0-py3.7.egg/scheduler_cli/scheduler_cli.py", line 260, in main
AttributeError: 'Namespace' object has no attribute 'func'
```
My install log is as follows:

```
$ python3 setup.py install
running install
running bdist_egg
running egg_info
creating scheduler_cli.egg-info
writing scheduler_cli.egg-info/PKG-INFO
writing dependency_links to scheduler_cli.egg-info/dependency_links.txt
writing entry points to scheduler_cli.egg-info/entry_points.txt
writing requirements to scheduler_cli.egg-info/requires.txt
writing top-level names to scheduler_cli.egg-info/top_level.txt
writing manifest file 'scheduler_cli.egg-info/SOURCES.txt'
reading manifest file 'scheduler_cli.egg-info/SOURCES.txt'
writing manifest file 'scheduler_cli.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/scheduler_cli
copying scheduler_cli/__init__.py -> build/lib/scheduler_cli
copying scheduler_cli/__main__.py -> build/lib/scheduler_cli
copying scheduler_cli/scheduler_cli.py -> build/lib/scheduler_cli
creating build/bdist.macosx-10.14-x86_64
creating build/bdist.macosx-10.14-x86_64/egg
creating build/bdist.macosx-10.14-x86_64/egg/scheduler_cli
copying build/lib/scheduler_cli/__init__.py -> build/bdist.macosx-10.14-x86_64/egg/scheduler_cli
copying build/lib/scheduler_cli/__main__.py -> build/bdist.macosx-10.14-x86_64/egg/scheduler_cli
copying build/lib/scheduler_cli/scheduler_cli.py -> build/bdist.macosx-10.14-x86_64/egg/scheduler_cli
byte-compiling build/bdist.macosx-10.14-x86_64/egg/scheduler_cli/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/scheduler_cli/__main__.py to __main__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/scheduler_cli/scheduler_cli.py to scheduler_cli.cpython-37.pyc
creating build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying scheduler_cli.egg-info/PKG-INFO -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying scheduler_cli.egg-info/SOURCES.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying scheduler_cli.egg-info/dependency_links.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying scheduler_cli.egg-info/entry_points.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying scheduler_cli.egg-info/requires.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying scheduler_cli.egg-info/top_level.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/scheduler_cli-2.2.2.0-py3.7.egg' and adding 'build/bdist.macosx-10.14-x86_64/egg' to it
removing 'build/bdist.macosx-10.14-x86_64/egg' (and everything under it)
Processing scheduler_cli-2.2.2.0-py3.7.egg
Copying scheduler_cli-2.2.2.0-py3.7.egg to /usr/local/lib/python3.7/site-packages
Adding scheduler-cli 2.2.2.0 to easy-install.pth file
Installing scheduler-cli script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/scheduler_cli-2.2.2.0-py3.7.egg
Processing dependencies for scheduler-cli==2.2.2.0
Searching for argparse
Reading https://pypi.org/simple/argparse/
Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl#sha256=c31647edb69fd3d465a847ea3157d37bed1f95f19760b11a47aa91c04b666314
Best match: argparse 1.4.0
Processing argparse-1.4.0-py2.py3-none-any.whl
Installing argparse-1.4.0-py2.py3-none-any.whl to /usr/local/lib/python3.7/site-packages
Adding argparse 1.4.0 to easy-install.pth file

Installed /usr/local/lib/python3.7/site-packages/argparse-1.4.0-py3.7.egg
Searching for boto3==1.9.84
Best match: boto3 1.9.84
Adding boto3 1.9.84 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for jmespath==0.9.3
Best match: jmespath 0.9.3
Adding jmespath 0.9.3 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for requests==2.21.0
Best match: requests 2.21.0
Adding requests 2.21.0 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for botocore==1.12.84
Best match: botocore 1.12.84
Adding botocore 1.12.84 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for s3transfer==0.1.13
Best match: s3transfer 0.1.13
Adding s3transfer 0.1.13 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for urllib3==1.24.1
Best match: urllib3 1.24.1
Adding urllib3 1.24.1 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for certifi==2018.11.29
Best match: certifi 2018.11.29
Adding certifi 2018.11.29 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for python-dateutil==2.7.5
Best match: python-dateutil 2.7.5
Adding python-dateutil 2.7.5 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for docutils==0.14
Best match: docutils 0.14
Adding docutils 0.14 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /User/Mark/Library/Python/3.7/lib/python/site-packages
Finished processing dependencies for scheduler-cli==2.2.2.0
```

**Comment by arieleeuw** [comment]
Hi,

The cli is developed for python version 2. Can you try using python or python2 ?

**Comment by mrichman** [comment]
Yes, it worked with Python 2.7. Any plans to update this framework to 3.7+? Python 2.x is EOL this year.

**Comment by arieleeuw** [comment]
We will put Python3 on our roadmap. The CLI just contains the code to collect the parameters it needs to make a call to the Instance Scheduler Lambda function. As it has no further logic we can update for Python3 separately from the rest of the code base.

**Comment by mrichman** [comment]
Sorry, I was unclear. I was actually referring primarily to upgrading the Lambda function to Python 3.

**Comment by shsenior** [comment]
Upgrading this solution to Python 3 is on our roadmap.
